/**
 * This program was generated by MetaShapes.
 * by MASOOD KAMANDY-MILNE
 */

PShape shape0;
PShape shape1;
PShape shape2;
PShape shape3;
PShape shape4;
PShape shape5;
PShape shape6;
PShape shape7;
PShape shape8;

void setup() {
  size(1000, 1000);
  noStroke();
  shapeMode(CENTER);
  shape0 = createShape(RECT, -200.0/2, -225.0, 200.0, 450.0);  shape1 = createShape(RECT, -200.0/2, -225.0, 200.0, 450.0);  shape2 = createShape(ELLIPSE, 0, 0, 100.0, 100.0);  shape3 = createShape(ELLIPSE, 0, 0, 100.0, 100.0);  shape4 = createShape(ELLIPSE, 0, 0, 40.0, 40.0);  shape5 = createShape(ELLIPSE, 0, 0, 40.0, 40.0);  shape6 = createShape(TRIANGLE, -57.735023, 33.333332, 57.735023, 33.333332, 0.0, -66.666664);
  shape7 = createShape(RECT, -30.0/2, -30.0, 30.0, 60.0);  shape8 = createShape(RECT, -30.0/2, -30.0, 30.0, 60.0);}

void draw(){
  background(-6750337);
  push();
  translate(276.0, 435.0);
  rotate(-4.123341);
  shape0.setFill(-8388609);
  shape(shape0, 0, 0);
  pop();
  push();
  translate(588.0, 409.0);
  rotate(-3.9269915);
  shape1.setFill(-8388609);
  shape(shape1, 0, 0);
  pop();
  push();
  translate(485.0, 492.0);
  rotate(0.0);
  shape2.setFill(-1);
  shape(shape2, 0, 0);
  pop();
  push();
  translate(794.0, 508.0);
  rotate(0.0);
  shape3.setFill(-1);
  shape(shape3, 0, 0);
  pop();
  push();
  translate(821.0, 525.0);
  rotate(0.0);
  shape4.setFill(-16777216);
  shape(shape4, 0, 0);
  pop();
  push();
  translate(507.0, 515.0);
  rotate(0.0);
  shape5.setFill(-16777216);
  shape(shape5, 0, 0);
  pop();
  push();
  translate(741.0, 788.0);
  rotate(-3.141593);
  shape6.setFill(-32897);
  shape(shape6, 0, 0);
  pop();
  push();
  translate(718.0, 894.0);
  rotate(0.0);
  shape7.setFill(-1);
  shape(shape7, 0, 0);
  pop();
  push();
  translate(755.0, 895.0);
  rotate(0.0);
  shape8.setFill(-1);
  shape(shape8, 0, 0);
  pop();
}